page_settings = {
    "003": {
        "speaker_name_window_threshold": 0.2
    },
    "004": {
        "speaker_name_window_threshold": 0.5
    },
    "005": {
        "speaker_name_window_threshold": 0.5
    },
    "007": {
        "speaker_name_window_threshold": 0.5
    },
    "008": {
        "speaker_name_window_threshold": 0.5
    },
    "030": {
        "speaker_name_window_threshold": 0.5
    },
    "041": {
        "speaker_name_window_threshold": 0.5,
    },
    "045": {
        "speaker_name_window_threshold": 0.5
    },
    "074": {
        "speaker_name_window_threshold": 0.1,
    },
    "080": {
        "speaker_name_window_threshold": 0.2
    },
    "101": {
        "speaker_name_window_threshold": 0.2,
    },
    "107": {
        "speaker_name_window_threshold": 0.2,
    },
    "130": {
        "speaker_name_window_threshold": 0.2
    },
    "152": {
        "speaker_name_window_threshold": 0.2
    },
    "190": {
        "speaker_name_window_threshold": 0.2
    }
}

# font names without prefix (e.g. 'ABCDEE+Verdana,Italic' -> 'Verdana,Italic')
italic_font_names = [
    'Arial-ItalicMT',
    'Arial-BoldItalicMT',
    'Helvetica-Oblique',
    'Calibri,Italic',
    'Verdana,Italic',
    'TimesNewRomanPS-BoldItalicMT',
    'TimesNewRomanPS-ItalicMT',
    'Arial,Italic',
    'MetaPlusBook-Italic',
    'Calibri,BoldItalic',
    'Times-Italic',
    'Helvetica,Italic',
    'Helvetica,BoldItalic',
    'Arial,BoldItalic',
    'Times-Italic',
    'Calibri-Italic',
    'Times-BoldItalic',
    'Times New Roman,BoldItalic',
    'SegoeUI-Italic',
    'Times New Roman,Italic',
    'Calibri-BoldItalic',
    'Verdana-BoldItalic',
    'Verdana-Italic',
    'Helvetica-Oblique',
    'Helvetica-BoldOblique',
    'Aptos,Italic',
]

# if any of these strings appear in a line, the line is ignored - case insensitive
ignore_line_markers = [
    'rocky-beach.com',
    'www.rocky-beach. com',
    'www. rocky-beach. com',
    'www. rocky-beach com',
    'www.rocky-beach.om',
    'Die drei ??? und der',
    'Die drei ??? und das',
    'Die drei ??? und die',
    'Die drei ??? -',
]

replacements = {
    # Hyphens
    '‐': '-',  
    '–': '-',  
    '—': '-',  
    # Quotes
    '‘': "'",   
    '’': "'",   
    '‚': "'",  
    '“': '"',   
    '”': '"',   
    '„': '"',  
    '´': "'",  
    '`': "'",
    '«': '"',  
    '»': '"',  
    # Ellipsis
    '…': '...',
    # Whitespaces
    "": " ",
    "": " ",
    "": " ",
}

additional_speakers = [
    'Justus', 'Bob', 'Peter', 'Elmquist', 'Murphy', 
    'Mr Prentice', 'Mrs Boogle', 'Ms Chalmers', 'Hassell', 
    'Peter, Bob', 'Justus, Peter', 'Tommy', 'Justua', 
    'Schwarzbart', 'Allgemein', 'Mrs.Peterson', 'DwiggIns', 
    '3???/ Gus', '3???', 'Gus', 'Rhandur', 'Dwiggins', 
    'Hitchcock', 'Mathilda', 'Allen', 'Shelby', 'Die ???', 
    'Reynolds', 'Carson', '1.Mann', '2.Mann', '3.Mann', 
    'Carlson', 'Calson', 'Green', 'Tonband', 'Just', 'Stimme',
    'Wikinger', 'Indianer', 'Radiostimme', 'Kapitän/Sam', 
    'Karl', 'Bob/Peter', 'Coulter/Sam', 'Ingmar', 'Manning',
    'Alle', 'B + J', 'P + B', 'Tai', 'Lama', 'Mr Zhang',
    'Mrs Carrera', 'Mrs Scott', 'Jeremy', 'Mr Acer',
    'Mrs Jones', 'Mr Cade', 'Mr. Brewster', '1. Polizist',
    'Beide Polizisten', 'Titus', 'Robinshaw', 'Peter.',
    'Cotta', 'Mrs. Hanson', 'Whitehead', 'Wright', 'Jusuts',
    'John+Jeffrey', 'White', 'Die ganze Sekte', 'Mr. Crowe',
    'Mr. MacGruder', 'Mr. Hanley', 'Connors', 'Demonstrant 1',
    'Demonstrant 2', '2. Polizist', 'Assistentin', 'Rossing',
    'Brackman', 'Amy', 'Monique', 'Cowley', 'Einer der Jungen',
    'Mr. Morland', 'Priscilla', 'Sicktree', 'PS', 'Wrenwick',
    'RW', 'Aishlyn', '???', 'Aishliy', 'Jonathan', 'Buck',
    'Mrs. Rodman', 'Valerie', 'Mr. Tillerman', 'Mr. Rodman',
    'Benjamin', 'Sgt. Morales', 'Skull', 'Duane Carpenter',
    '1. Reporterin', '2. Reporterin', 'Francis Stdstill',
    'Mr. Woodland', 'Mr. Norsworthy', 'Mr. Wellford', 'Justs',
    'Francis oder Carol', 'Einer der Männer', '3 ???',
    'Mrs. Sullivan', 'Mr. Taylor', 'Susan', 'Bob, Peter',
    'Peter, Susan', 'Justus, Bob', 'Bob, Susan', 'Julia',
    'Mrs. Hutchinson', 'Mrs. Claire Jordan', 'Wolf', 'Mr Qin',
    'Peter, Justus, Bob (unisono)', 'Verstellte Stimme',
    'Christopher Barcley', 'Mr. Godfrey', 'Harper Knowsley',
    'Knowsley', '„Bob“ Bill Cooper', 'Mr Appelgate', 'Godween',
    'Mr Farnham', 'Bob/Justus', 'Justus/Peter', 'Die drei ???',
    'Mr. Diffleton', 'Justus, Peter, Bob', 'Justus, Bob',
    'Mr. Sinclair', 'Bob, Justus', 'Barnaby Witherspoon',
    'Prof. Mathewson', 'Die drei Jungen', 'Fiona', '1. Mann',
    'Vanessa Gooldstein', 'Vanessa Goldstein', '2. Mann',
    'Rossing', 'Assistentin', 'Brackman', 'Fletcher', 'Nobel',
    'Pherson', 'Justus/Peter', 'Justus/Bob', 'Laurent', 'Ray',
    'Mr. Laurent', 'Hannah Harding', 'Carpenter', 'Contreras',
    'Stapleton', 'Bob, Peter und Mrs. Harding', 'Ambler', 
    'Harding', 'Die Fragezeichen und Cotta', 'Rodder', 'Cris',
    'Mr. Hitchcock', 'Mr. Denton', 'Mr. Farraday', 'Skinny',
    'Pico', 'Peter, Justus', 'Allie', 'Tante Patricia', 
    'Miss Osborne', 'Bentley', 'Mrs. Compton', 'Hendricks',
    'Bettler', 'Bob, Allie', 'Doktor', 'Dick Miller', 'Jenny',
    'Justsu', 'Publikum', 'Mrs.Darnley', 'Mrs.Darley',
    'Santora', 'Mrs.Darnely', 'Mr.Andersen', 'Mr.Anderson',
    'Mr. Donner', 'Arbeiter', 'Mr. Slater',
    'Retter1',
'Retter2',
'Beide',
'Sprecher',
'Mr. Fentriss',
'Waggoner',
'Mr. Claudius',
'O. Ramos',
'Onkel',
'Ramos',
'Blackbeard',
'Hugenay',
'1. Mitarbeiterin',
'2. Mitarbeiterin',
'Stebbins',
'Flora',
'Cluny',
'Mr. Maximilan',
'Totenkopf',
'Juana',
'K. Reynolds',
'Mrs Miller',
'Totenkopf',
'Simpson',
'Prof. Carswell',
'Hal',
'Marechal',
'Hal, Bob',
'Peter, Hal',
'Wilkins',
'Yarborough',
'Rex',
'1. Araber',
'2. Araber',
'Rosa',
'Rex',
'Grand',
'Rex/Terrill',
'Terrill',
'Ted',
'Mrs Hammond',
'Smathers',
'Mr Richardson',
'Mr. Hall',
'Callow',
'Drei ???',
'Ballinger',
'Mr. Dalton',
'Jackson',
'Turner',
'Reston',
'Eftimin',
'Tina',
'Teufel',
'Mr. Kastner',
'Frankie',
'Teufel',
'Quail',
'Hummer',
'Wilkes',
'Clay',
'Mr. Frank',
'Wachmann',
'Mr. Togati',
'Hitchcock',
'Agawam',
'Erzähler',
'Bob, Peter',
'Jordan',
'Rawley',
'Taro',
'Chuck',
'Liliputaner',
'Patrick',
'Lars',
'Forsberg',
'Bert',
'Johann',
'Mr. Atkinson',
'Beefy',
'William',
'Mr. Gray',
'Mr. Grear',
'Madeleine',
'Mr. Long',
'Ms. Adams',
'Ndula',
'Hotelchef',
'Ian',
'Hitfield',
'Don',
'Tuckerman',
'Die drei Fragezeichen',
'Bonestell',
'Strong',
'Mr. Malz',
'Mrs. Radford',
'Elsie',
'Mr. Evans',
'Hubert',
'Mr. Shaw',
'Teriano',
'Mr. Wolfe',
'DiStefano',
'Miss Peabody',
'Mr. Burton',
'alter Mann',
'Mr. Snabel',
'Ms. Melody',
'Japaner',
'Anderson',
'Pfandleiher',
'Glass',
'Fotografen',
'Shatterhand',
'Flapjack',
'Trixie',
'Mr. Burnside',
'Marilyn',
'Mr. Pilcher',
'Sanchez',
'Mr. Durham',
'Westerbrook',
'Ramon',
'Mr. Andrews',
'drei ???',
'Turner',
'Nancarrow',
'Biff',
'DeMento',
'Rottweiler',
'Trash',
'Mr. Griswold',
'Rainey',
'Morningbaum',
'Ackbourne-Smith',
'Mr. Morningbaum',
'Gast',
'Dustin Rice',
'Ascensión',
'Brit/Justus',
'Sax Sendler',
'J. H. Butler',
'Lara',
'MacTavish',
'Ty',
'Peter, Bob, Maxi',
'Cole',
'Maxim',
'Mr. Torres',
'Gracie',
'El Tiburón',
'Hatch',
'Mr. Gilbar',
'Mr. Firestone',
'Lowell Madera',
'Wick Hamil',
'Wick',
'Mr. Harper',
'„Michael Anthony“',
'„Anthony“',
'Mr. Norman',
'Duggan',
'Mr. Ek',
'Elisabeth',
'Yan',
'Branson',
'Rome',
'Pecker',
'Chosmo',
'Van Well',
'Jaubert',
'Jean Baxter',
'Jean',
'Sinagua',
'René',
'Joan',
'Hendrik Walton',
'Landman',
'Field',
'Glenn',
'Descanso',
'Hutchins',
'Andrews',
'Dieb',
'Stadionsprecher',
'Hutchins',
'Landman',
'1.Polizist',
'2.Polizist',
'Clint Adams',
'Amanda',
'Mr. Simpson',
'Silverstone',
'Mr. Jones',
'Verkäuferin',
'Jimboy',
'Portier',
'Bow',
'Mostovsky',
'Alexander Burlington',
'Mr. Rodriguez',
'Teilnehmer',
#'Drei Fragezeichen',
'Ignazio',
'Sofia',
'Spinne',
'Unbekannte',
'Babette',
'Br. Benedikt',
'Koch',
'Emil Mylnár',
'Mr Brady',
'Mrs Fiedler',
'Model',
'Sally',
'Besucherin',
'Mrs. Jenkins',
'Mrs. Fiedler',
'Washington',
'Sofie',
'Lautsprecher',
'Mister Jefferson',
'Mister Dimitrios',
'Raul Santoria',
'Lu Kwan',
'Telefonist',
'McLaughin',
'Copper',
'Sinclair',
'Walsh',
'Lansana',
'Inspector Kershaw',
'Museumsbedienstete',
'Miss Madigan',
'Eathon Easton',
'Lydia Cartier',
'Sigourney',
'Gregston',
'Mrs Atson',
'Krieger',
'Metzla',
'Mrs. Holligan',
'Dr. Franklin',
'Cliffwater',
'Telefonist',
'MacMannoman',
'Needle',
'Peter/Bob',
'Mrs Fletcher',
'Mr Fletcher',
'Mrs Jonas',
'Toni',
'Julio DaElba',
'Justus, Peter, Bob',
'Mrs Summer',
'Mr Art',
'Prof. Steed',
'Mr Hanson',
'Dr. Helprin',
'Mr.Andrews',
'Vanderhell',
'Jelena',
'Mr. Peacock',
'Polizisten',
'Kundin',
'Doe Dungeon',
'Lili Bushford',
'Peter&Bob',
'Bob&Peter',
'MacDunno',
'Moore',
'Black',
'Mr. Shaw',
'Mr Copper',
'Mr Carter',
'Mr Jackson',
'Lilly',
'Mr Steward',
'Charkov',
'Janet',
'Feuerwehr',
'Franks',
'Mrs Shaw',
'Ferguson',
'Mr Smith',
'Paradise',
'Rawlings',
'Mrs. Hazelwood',
'Mrs White',
'Mr. Messway',
'Johnny',
'Prof. Phoenix',
'Prof. Phoenix, Dr. Svenson, Al & Juan',
'Prof. Phoenix, Al & Juan',
'Funkgerät',
'Soldat',
'TV-Erzähler',
'Werbefrau',
'Jeremiah King',
'Harvey Radcliffe',
'Mr Falkner',
'Mr Masterson',
'Mrs Masterson',
'Barkeeperin',
'Verzerrte Stimme',
'Mrs Sutton',
'Mr Sharky',
'Betty Sutton',
'Mrs Wood',
'Mrs Baker',
'Pirat',
'Peter/Justus',
'Lythia',
'J. Donelly',
'J. Fairbanks',
'J. Stanley',
'Henker',
'Flemings',
'Die Fragezeichen',
'Brad Flemings',
'Ewan Donovan',
'Lake',
'Dr. Tiberius Wakefield',
'Mrs Willow',
'die drei Jungen',
'mehrere',
'alle',
'Horowitz',
'Anrufbeantworter',
'Frauenstimme',
'Caitlin',
'Craig',
'Die Fragezeichen',
'Parker',
'Die drei Detektive',
'McQuire',
'Reno',
'Jaccard',
'Graham',
'LKW- Fahrer',
'Knox',
'Dr. Timothy Chandler',
'Chandler',
'Bright',
'Justus/Peter/Bob',
'Anrufbeantworter',
'Inspektor Cotta',
'Mr. Crowle',
'Mr. Abazza',
'Felicia',
'Mrs. Sparing',
'Justus, Bob, Peter',
'Erroll',
'Prof. Alkurah',
'Ganove 1',
'Ganove 2',
'Ganove 3',
'Ganove 4',
'Ganove 5',
'Ganove 6',
'Ganove 7',
'Ganove 8',
'Sgt. Ludlow',
'C. Harkinson',
'männliche Stimme',
'Elvira',
'Dr. Holloway',
'Darren',
'Carl',
'Die anderen',
'Davy',
'Peter, Davy',
'Putzmann',
'Justus, Bob, Peter',
'Davy, Bob',
'Davy, Peter',
'Justus, Bob, Davy',
'Dorfbewohner',
'Otis',
'Sylvester',
'Jacki Jon',
'Barnaby Witherspoon',
'Der Meister:',
'Takai Yukawa',
'Takasi Yikawa',
'Winston Wadleigh',
'Sammy/Jamie',
'Mr. Waterfield',
'Jackall Madsen',
'Dr. Frears',
'Tiger Madsen',
'Sammy/Jamie',
'Geisterstimme',
'Vermummter',
'Wever o. Prescott',
'Mrs. McGowan',
'Mr. Fraser',
'Mina',
'Beatrix',
'Mr. Davis',
'Curtis Fishe',
'Mrs: Maruthers',
'Mr. Chilton',
'Sportreporter',
'Komplize',
'Prof. Heathcliff',
'Mr. Burk',
'Miss Cassidy',
'Kom. Reynolds',
'Handlanger',
'Mt. Torrance',
'Mr. Holbrooke',
'Mrs. Holbrooke',
'Guinevere',
'Fred',
'Mr. Hunnicutt',
'Frauenstimme',
'Mr. Gizmo',
'Mr. Chester',
'Mr. Greenwalt',
'Goodwin',
'Mr. Deforge',
'Prof. Brewster',
'Mr. Sesto',
'Mr. Holt',
'Mr. Tornby',
'Petre',
'Teufelsgestalt',
'Andere Spieler',
'Anrufbeantworter',
'Jeanny Chase',
'Mr. Lewis',
'Grey',
'Mrs. Pembroke',
'Mr. Vaughn',
'The Destroyer',
'Earl',
'Peter, Luke und Bob',
'Mr. Cray',
'Mrs. Farnham',
'Mrs Farnham',
'Grace',
'Quadfahrer',
'Mr Bright',
'Mr Andrews',
'Mrs Breckenridge',
'Mr Garvine',
'Studentin',
'Mr Roalstad',
'Studentenmenge',
'Erster Polizist',
'Zweiter Polizist',
'Mr Walker',
'Mrs Roalstad',
'Mr Roalstad',
'Garvine',
'Mrs Fernandez',
'Dr Wilcomb',
'Mr Andrews',
'Mrs Fernandez',
'Mrs Breckenridge',
'Leslie Louge Smith',
'Vermummte',
'Dr. Burke',
'Neill Hooper',
'Cecil Arbuthnott',
'Ronald Smith',
'JPB',
'RS',
'"Phantom"',
"O'Sullivan",
"Mrs. O'Rien",
"Mrs. O'Donnell",
"O'Brian",
'Morten',
'McDermott',
'Dusty',
'Holly',
'Weibliche Stimme',
'Miranda',
'Justrus',
'Mrs Cooper',
'Mathilda Jonas',
"Kenneth O'Ryan",
'Titus Jonas',
'Peter und Bob',
'Peter und Justus',
'Mr Rice',
'Katee Parker',
'Geronimo Johnson',
'Tricia Copper',
'Sergeant Cooper',
"Patrick O'Ryan",
'Männlicher Gast',
'Weiblicher Gast',
'Chief Hoouseholder',
'Gäste',
'1 niederl.',
'2 niederl.',
'3 niederl.',
'Meister. Spezialität',
'Alle sagen',
'Mister Felix',
'Peter und Bob',
'Mrs. Smith',
'Mister Jenkins',
'Alle drei',
'Justus und Peter',
'Gerald Kramer',
'Justus',
'Mr.Hall',
'Stimme aus Funkgerät',
'Erster Detektiv',
'Historiker',
'Mrs. Durham',
'P.u.J.',
'PuB',
'P.u.B.',
'PuB,Mary',
'Griswold',
'Mrs. Fields',
'Justus und Bob',
'Peter und Bob',
'Bob',
'Peter, Bob, Tony',
'Bass Newman',
'Bass',
'Judy Callman',
'Judy',
'Mann1',
'Mann4',
'Luis',
'Jim Bernady',
'Justus',
'Mr. Crocker',
'Peter',
'Kelly',
'Peter',
'Lowell',
'George',
"George &' Bob",
'Personen',
'Justus',
'Lowell',
'John Worren',
'Peter',
'Dávid',
"Justus &' Bob",
"Peter &' Bob",
'Viele Mädchen',
'Peter & Bob',
'Justus Jonas',
'Peter Shaw',
'Axel Hamilton',
'Lys de Kerk',
'Justus und Peter',
'Virginia Bloomingdale',
'Virginia',
'Miss Clayburn',
'Stella Ashley',
'Justus Jonas',
'Bob und Peter',
'Walton',
'Demonstranten',
'Demonstrantin',
'Anne Baxter',
'Justus und Bob',
'Bob & Peter',
'Michael Oames',
'Justus und Peter',
'Gruppe und Peter',
'Stimme 1',
'Dan Jordan',
'Peter und Bob',
'Justus und Bob',
'Justus und Peter',
'Kelly',
'Peter',
'Bob',
'Hugenay',
'Männerstimme',
'Mrs. Maggie Seven',
'Peter Shaw',
'Justus Jonas',
'Bob und Peter',
'Speed-Mann',
'Trainer Roger',
'Peter und Bob',
'Karen und Bob',
'Nicola Schalla',
'Streckenposten Henry',
'Alle vier',
'Justus und Bob',
'Bob und Peter',
'Alle drei',
'Prof Steed',
'Kapitän Jason',
'Peter & Bob',
'Peter und Justus',
'Justus und Peter',
'Justus Jonas',
'Joe Stapleton',
'Sandy Allen',
'Peter Shaw',
'Peter und Bob',
'Scott Ambler',
'Peter und Justus',
'Jeff Rodder',
'Justus und Bob',
'Schrille Stimme',
'Mr. Qin',
'Bob / Peter',
'Justus und Bob',
'Mr Cooper',
'Frau des Bürgermeister',
'Bob und Peter',
'Mr Jackon',
'Alle drei',
'Mr Stewart',
'Alle drei',
'Peter',
'Stimmen',
'Skinny',
'Dr. Svenson',
'Juan',
'Justus, Peter & Bob',
'Echo',
'Al, Dr. Svenson & Juan',
'Justus & Peter',
'Peter und Bob',
'Bob und Peter',
'Barbara Stevens',
'Peter und Bob',
'Alle drei',
'Alle Jungs',
'Bob und Peter',
'Justus & Bob',
'Professor Clark',
'Peter & Bob',
'Peter Shaw',
'Justus Jonas',
'Justus und Peter',
'Pit Jones',
'Justus und Bob',
'Kleiner Fuchs',
'Peter Shaw',
'Justus Jonas',
'Emily Silverstone',
'Peter und Justus',
'Justus und Bob',
'Peter und Bob',
'Bob und Peter',
'Justus und Bob',
'Bob und Peter',
'Phantomstimme',
'Mrs. Willows',
'Bob & Peter',
'Peter & Bob',
'Bob & Justus',
'Samuel Rothman',
'Justus & Bob',
'Computerstimme 1',
'Computerstimme 2',
'Justus, Titus',
'Magthilda',
'Skinner',
'Goodwyn',
'Peter Shaw',
'Peter und Bob',
'Alle drei',
'Peter und Justus',
'Bob und Peter',
'Martha Lynn',
'Mann in der Kirche',
'Bob und Justus',
'Dr. Sotherby',
'Peter & Justus',
'Ms. Lloyd',
'Mr. Thorndike',
'Mr. Thondike',
'Mr. Boyd',
'Peter Shaw',
'Justus Jonas',
'Fragezeichen',
'Peter und Bob',
'Frank Campbell',
'Campbell',
'Bob und Justus',
'Peter und Justus',
'William Kingsley',
'Sarah Kingsley',
'Dr. Philip Long',
'Kingsley',
'Alle Drei',
'Peter & Bob',
'Justus & Bob',
'Hugenay',
'Bob& Justus',
'Morton',
'Peter& Bob',
'Justus& Bob',
'Peter& Justus',
'Mrs.Wallace',
'Peter Shaw',
'Justus Jonas',
'Max Dutton',
'Austin Barfield',
'Bob und Peter',
'Justus und Peter',
'Peter und Bob',
'4 nicht ganz richtig',
'Albert Monroe',
'Monroe',
'Smith',
'Retter',
'Justus + Peter',
'Justus + Peter + Bob',
'Justus + Bob',
'Peter + Bob',
'Bob + Cotta',
'Bob und Peter',
'Anrufbeantworter-Bob',
'Mr. Taper',
'Peter und Bob',
'Justus und Peter',
'Bob und Peter',
'Bob und Justus',
'Alle drei',
'Officer Johnson',
'Prof Alkurah',
'Peter & Bob',
'Justus & Peter',
'Mönch',
'Hurst',
'Justus Jonas',
'Peter Shaw',
'Peter / Bob',
'Peter und Bob',
'Darrem',
'Dr Holloway',
'WinstonGranville',
'MatthewGranville',
'Mr.Jackmore',
'ProfessorFrazier',
'Titus Jonas',
'Justus & Peter',
'Alle Drei',
'Justus und Bob',
'Justus und Peter',
'Peter und Bob',
'Sylvester Proud',
'Menschenmenge',
'Mr. Chinks',
'Seaman',
'Erster Detektiv',
'Archiv',
'Schakal-Mensch',
'de Haas',
'Justus und Peter',
'Peter und Bob',
'Carol Fox',
'Bob und Justus',
'Bob & Peter',
'Peter & Bob',
'Justus Jonas',
'Alle Drei',
'Justus & Peter',
'Der Meister',
'Alle Schüler',
'John Frears',
'Justus, Jamie',
'Justus und Peter',
'Max Wever',
'Edward Crocket',
'Justus und Peter',
'Justus und Bob',
'Ursula Burns',
'Peter und Bob',
'Allie Jamison',
'Der andere Mann',
'Bob und Roxy',
'Justus & Peter',
'Rank Mason',
'Dergeant Madhu',
'Justus & Bob',
'Peter & Bob',
'Tony Amoroso',
'Peter und Bob',
'Frau bei Polizei',
'Justus und Peter',
'Mr, Chilton',
"Mr. O'Donnell",
'Justus & Peter',
'Peter & Bob',
'Justus & Bob',
'Alle Drei',
'Sheriff Picket',
'Cole Benedict',
'Justus und Peter',
'Mr. Holbrook',
'Peter und Bob',
'Bob und Peter',
'Sheila Masters',
'Peter und Bob',
'Jenna',
'Justus und Bob',
'Peter und Bob',
'Justus und Peter',
'Bob und Peter',
'Peter und Just',
'Peter und Justus',
'Bob und Peter',
'Peter und Bob',
'Prof Brewster',
'Mr. Cobble',
'Fynch Hunterman',
'Peter und Bob',
'Bob und Justus',
'Justus und Peter',
'Fynch und Justus',
'Lenni Carson',
'Justus & Peter',
'Justus, Peter & Bob',
'Justus & Bob',
'Alle zusammen',
'Randy Chase',
'Peter und Bob',
'Jeanne Chase',
'Tara Finn',
'Peter und Randy',
'Ginette Giorgianis',
'Justus und Bob',
'Ranger Thronton',
'Nash Grayston',
'July Nigel',
'Bob und Peter',
'Peter und Bob',
'Mrs. Rodman',
'Bob und Cotta',
'Peter Shaw',
'Justus Jonas',
'Justus und Peter',
'Bob und Peter',
'Justus Jonas',
'Peter Shaw',
'Fragezeichen',
'Mr. Faring',
'Thomas Malone',
'Crane',
'Jupe',
'Peter + Justus',
'Sanitäter Matt',
'Sanitäter Stephen',
'Juan Gonzales',
'Telefondurchsage',
'Puppe',
'Puppe 2',
'Puppe 3',
'Puppen',
'Anderer Mann',
'April und Joshua',
'Alle Jungen',
'Peter und Bob',
'Mortimer Sisko',
'Sandra Martinez',
'Fernseher',
'Fernseherstimme',
'Mr. Penny',
'Justus & Bob',
'Justus, Peter & Bob',
'Justus & Bob',
'Peter & Bob',
'Laura Berret',
'Amber Berret',
'Gerald Berret',
'Stewart Collins',
'Peter und Justus',
'Stimme vom AB',
'Justus & Peter',
'Peter & Justus',
'Peter und Bob',
'Andy McBranton',
'Justus und Peter',
'Bob und Justus',
'Bob und Peter',
'Justus und Bob',
'Justus und Bruce',
'Jeff Renalso',
'Bruce Jeff',
'Inspektorin',
'Folder',
'Augenzeugin',
'Dr. Hopper',
'Justus Jonas',
'Mr Giggles',
'Frank Corman',
'Peter + Justus',
'Mr Henson',
'Mrs Planter',
'Bob und Peter',
'Agent Ross',
'Agent Wright',
'Jornnn',
'Ms Bowman',
'Bob und Peter',
'Huxley',
'Mr Credic',
'Mr Shuiver',
'Mrs Shuiver',
'Mrs S',
'Peter und Bob',
'Mathilda Jonas',
"Kenneth O'Ryan",
'Titus Jonas',
'Peter und Bob',
'Peter und Justus',
'Mr Rice',
'Katee Parker',
'Geronimo Johnson',
'Kenneth O`Ryan',
'Tricia Copper',
'Tricia Cooper',
'Sergeant Cooper',
"Patrick O'Ryan",
'Männlicher Gast',
'Weiblicher Gast',
'Chief Hoouseholder',
'Gäste',
'Mr.Shaw',
'Mr.Evans',
'Mr. Duggan',
'Shirley',
'Mr. Sears',
'Winkler',
'Br. Raphael',
'Inspektor',
'Ober',
'Pat',
'Rosenberg',
'Mr Cray',
'Farnham',
'Mr Lloyd',
'Jsuts',
]